### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/seaql.github.io#1]
![image](https://user-images.githubusercontent.com/1782664/126871678-108b62f0-73b0-4e29-87be-d095663ed6bf.png)

https://www.sea-ql.org/SeaORM/docs/write-test/sqlite

This example is not illustrative enough. We need some asserts.

And perhaps we can copy a more real example from our test suite, like 'create_order'

**Comment by billy1624** [comment]
But our updated test suit is targeted to run on MySQL for now. Perhaps I will update the doc after the updates completed?

**Comment by tyt2y3** [comment]
There is not too much database specific code right?

**Comment by billy1624** [comment]
We use UUID in test suit?

**Comment by billy1624** [comment]
Yes, UUID & decimal are "supported" in Sqlite.

https://github.com/SeaQL/sea-query/blob/9a8806221a1392302faea00dc49fd513457d0ee8/src/backend/sqlite/table.rs#L38-L109

**Comment by billy1624** [comment]
The special struct we used in `Model`, all are supported by all three databases except for `rust_decimal::Decimal`
- `uuid::Uuid`
- `rust_decimal::Decimal` (not supported by sqlx-sqlite)
- `chrono::NaiveDateTime`

The supported rust types of each database in Sqlx

- https://docs.rs/sqlx/0.5.5/sqlx/mysql/struct.MySql.html
- https://docs.rs/sqlx/0.5.5/sqlx/postgres/struct.Postgres.html
- https://docs.rs/sqlx/0.5.5/sqlx/sqlite/struct.Sqlite.html

**Comment by tyt2y3** [comment]
Yes sure lets pick a small example

**Comment by tyt2y3** [comment]
https://www.sea-ql.org/SeaORM/docs/basic-crud/raw-sql-and-json
Add also examples for:
1. the raw `query_*` API (on `DbConn` and using `QueryResult`
2. the raw `execute` API
3. some asserts for the JSON results

**Comment by billy1624** [comment]
Updated, please check
- https://www.sea-ql.org/SeaORM/docs/basic-crud/json
- https://www.sea-ql.org/SeaORM/docs/basic-crud/raw-sql
