### ISSUE TITLE
Enable HTTPS? Indian ISP performing MITM attack?

### ISSUE THREAD

**Issue by iamsauravsharma** [SeaQL/seaql.github.io#12]
I currently cannot access the website I am only seeing blank page similar to issue discussed  https://discourse.nodered.org/t/nodered-site-is-blocked-india/49645 or https://community.cloudflare.com/t/website-blocked-for-some-users-in-india/300620 (Same IP address redirection and IP address in source of page). https://community.cloudflare.com/t/website-blocked-for-some-users-in-india/300620/5 is recommending to enable HTTPS if you have not enabled it for GitHub Pages. Can you guys implement that solution to enable GitHub Pages HTTPS (direct link to GitHub Docs: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https)?

**Comment by psibi** [comment]
Facing the the same issue. Using an IP address from US solves it for me. But yeah, it would be nice to get this fixed. :-)

**Comment by iamsauravsharma** [comment]
@tyt2y3 @billy1624  More details about issue related to MITM attack along with better solution is present at [captn3m0/hello-cloudflare](https://github.com/captn3m0/hello-cloudflare)

**Comment by billy1624** [comment]
Can we enabled the HTTPS settings on GitHub? @tyt2y3

**Comment by captn3m0** [comment]
Note that you need to enable Strict SSL at CloudFlare end _in addition to GitHub Pages side for the fix to work. 

Here's the direct link on how to fix: https://github.com/captn3m0/hello-cloudflare/blob/main/README.md#help-my-website-is-blocked

Added seaql.github.io to the list.

**Comment by tyt2y3** [comment]
Thanks for the tips! I will try again

**Comment by tyt2y3** [comment]
![image](https://user-images.githubusercontent.com/1782664/151911861-7ca3bf40-50a7-4264-96bf-2a66177ebe94.png)

I should have fixed this for now. If there are still problems, let me know.
