### ISSUE TITLE
Broken links on documentation pages

### ISSUE THREAD

**Issue by paul-hansen** [SeaQL/seaql.github.io#129]
The page: https://www.sea-ql.org/SeaORM/docs/basic-crud/select/
Contains these broken links:
[filter](https://docs.rs/sea-orm/*/sea_orm/entity/prelude/trait.QueryFilter.html#method.filter)
[find_related](https://docs.rs/sea-orm/*/sea_orm/entity/prelude/trait.ModelTrait.html#method.find_related)
[find_also_related](https://docs.rs/sea-orm/*/sea_orm/entity/prelude/struct.Select.html#method.find_also_related)
[find_with_related](https://docs.rs/sea-orm/*/sea_orm/entity/prelude/struct.Select.html#method.find_with_related)

It appears back around 0.6 these were included in the entity::prelude so they worked then. For example, adding the version 0.6 to the url makes them work.
Doesn't work: 
https://docs.rs/sea-orm/*/sea_orm/entity/prelude/struct.Select.html#method.find_also_related
Works:
https://docs.rs/sea-orm/0.6/sea_orm/entity/prelude/struct.Select.html#method.find_also_related
https://docs.rs/sea-orm/*/sea_orm/query/struct.Select.html#method.find_also_related

Might want to consider doing something to discover other broken links and perhaps add version numbers to docs.rs links so they don't break in the future.

**Comment by tyt2y3** [comment]
Thanks for reporting. Can you submit a PR to fix those with the non-prelude links?
