### ISSUE TITLE
SeaORM Tutorial

### ISSUE THREAD

**Issue by billy1624** [SeaQL/seaql.github.io#14]
## Tutorial 1: The Basic & CRUD

1. What is SeaORM
1. Defining Entity
1. Configuring Connection
1. Setting Up Database Schema
1. CRUD
    - Insert
    - Select
    - Update
    - Delete
    - Save

## Tutorial 2: Relations

1. Defining Basic Relations with `Related` Trait
    1. One to One
    1. One to Many
    1. Many to Many
1. Finding `Related` Models
    1. Lazy Loading
    1. Eager Loading
1. Defining Advanced Relations with `Linked` Trait
    1. Chained Relations
    1. Self Referencing
1. Finding `Linked` Models
    1. Lazy Loading
    1. Eager Loading

## Tutorial 3: Unit Test on Mock Connection

1. Setting Up Mock Connection
    1. Query Result
    1. Execution Result
1. Performing Unit Tests
1. Asserting Transaction Log

## Tutorial 4: Integration Test on SQLite

1. Setting Up Connection
1. Setting Up Database Schema
1. Performing Integration Tests

## Tutorial 5: Advanced Select

1. Paginator
1. Streaming
1. Select Model as Json
1. Query by Raw SQL
1. Select Custom or Partial Columns
1. Conditional Expressions
1. Aggregations
1. Custom Joins
1. Subquery

## Tutorial 6: Advanced Insert, Update & Delete

1. Transaction
1. Custom Active Model
1. Insert Many
1. Update Many
1. Delete Many

**Comment by tyt2y3** [comment]
OH this series seems too long and probably will duplicate a lot of what the documentation already explains.
I think a short, concise, from scratch "Getting Started" article will be enough.
