### ISSUE TITLE
How to add a site map?

### ISSUE THREAD

**Issue by tyt2y3** [SeaQL/seaql.github.io#4]
![image](https://user-images.githubusercontent.com/1782664/129907051-ffd37023-49bb-4bb7-a7ba-d179379ee9a1.png)

![image](https://user-images.githubusercontent.com/1782664/129907007-78de9dfb-773a-4672-8f41-ddef750faa26.png)

**Comment by tyt2y3** [comment]
![image](https://user-images.githubusercontent.com/1782664/129918196-83154acd-e1ce-43f9-a8c4-5f4c4bd6dfea.png)
🤔

**Comment by billy1624** [comment]
I guess we need this?
https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#addsitemap

Send a GET request to... https://www.google.com/ping?sitemap=https://www.sea-ql.org/SeaORM/sitemap.xml

**Comment by tyt2y3** [comment]
My ideal look:
```
SeaORM - 🐚 An async & dynamic ORM for Rust
SeaORM is a relational ORM to help you build light weight and concurrent web services in Rust.
Getting Started | API Reference | About Us | Blog
```
