### ISSUE TITLE
What's new in SeaQuery 0.26.0

### ISSUE THREAD

**Issue by billy1624** [SeaQL/seaql.github.io#42]
We'd like to have release blog post for SeaQuery as well. Similar to what SeaORM has, e.g. [What's new in SeaORM 0.9.0](https://www.sea-ql.org/SeaORM/blog/2022-07-17-whats-new-in-0.9.0/)

**Comment by billy1624** [comment]
CC @ikrivosheev

**Comment by ikrivosheev** [comment]
@billy1624 yep, I do this)

**Comment by billy1624** [comment]
Thanks! @ikrivosheev

**Comment by billy1624** [comment]
Please add the blog post to https://github.com/SeaQL/seaql.github.io/tree/master/SeaORM/blog directory. I will setup a organization wide blog later, https://github.com/SeaQL/seaql.github.io/issues/43.

**Comment by billy1624** [comment]
Hey @ikrivosheev, I just added https://www.sea-ql.org/blog/

**Comment by tyt2y3** [comment]
Like this idea :)
