### ISSUE TITLE
SeaQL organization wide blog

### ISSUE THREAD

**Issue by billy1624** [SeaQL/seaql.github.io#43]
## Motivation

We'd like to have a organization wide blog for all of our news and release blog posts. All served under the url: `www.sea-ql.org/blog`

## Proposed Solutions

1. Make www.sea-ql.org a Docusaurus site with SeaQL org landing page and blog

2. Redirect all `www.sea-ql.org/SeaORM/blog/xxx` to `www.sea-ql.org/blog/xxx`. This tool provided by Docusaurus might be helpful: https://docusaurus.io/docs/2.0.0-beta.22/api/plugins/@docusaurus/plugin-client-redirects

**Comment by tyt2y3** [comment]
Awesome / cool / great!
